name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Get Version
        id: version
        run: echo "version=$(cargo pkgid | cut -d '#' -f2)" >> $GITHUB_OUTPUT
      - name: Build
        id: build
        run: cargo build --release --verbose
      - name: Upload
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: tdnab-${{ steps.version.outputs.version }}-${{ runner.os }}_${{ runner.arch }}
          path: target/release/tdnab
